services:
  - docker                  

# safelist
branches:
  only:
  - published_version

before_install:            
  - docker pull rocker/r-rmd

before_script:
  - chmod +x ./_build.sh

script:
  - docker run  --rm -v $(pwd):/documents --name bookdown rocker/r-rmd  /documents/_build.sh

after_error: 
  - docker logs bookdown

after_failure:
  - docker logs bookdown

deploy:
  - provider: pages
    local_dir: _book/
    skip-cleanup: true
    github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    target-branch: gh-pages
    on:
      branch: master
