services:
  - docker                  

# safelist
branches:
  only:
  - master

before_install:            
  - docker pull conoria/alpine-r-bookdown

before_script:
  - chmod +x ./_build.sh

script:
  - docker run  --rm -v $(pwd):/documents --name bookdown conoria/alpine-r-bookdown  /documents/_build.sh

after_error: 
  - docker logs bookdown

after_failure:
  - docker logs bookdown


deploy:
  - provider: pages
    local_dir: _book/
    skip-cleanup: true
    github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    target-branch: gh-pages
    on:
      branch: master
  - provider: pages
    local_dir: _book/
    skip-cleanup: true
    github-token: $GH_TOKEN_DEV
    keep-history: true
    target-branch: gh-pages
    repo:  labordynamicsinstitute/idea-handbook-7a434a70-04c1-4400-883b-db0e5f1fa653 
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != master
